## Curso de Manipulacion y Transformacion de Datos con Pandas y Numpy

## **Numpy Array**

In [1]:
import numpy as np 
import pandas as pd 

### **Array**
* La estructura central de Numpy 
* Representa datos de manera estructurada
* Indexado
* Acceso a uno o muchos elementos

In [2]:
lista = [0,1,2,3,4,5,6,7,8,9]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [4]:
matriz = ([1,2,3],[4,5,6],[7,8,9])
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matriz [0,2]

3

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Slicing**

In [7]:
arr
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
arr = np.array(lista)
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'],
      dtype='|S21')

### **Dimensiones**

In [9]:
# Definiendo un scalar
scalar = np.array(42)
print (scalar)
scalar.ndim

42


0

In [10]:
# Definiendo un vector
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [11]:
# Definiendo una matriz
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

### **Creando Arrays**

In [12]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# Esto es util para crear array de iteracion o de imagenes con tamaños definidos
np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Linspace Hace una distribucion de los datos con un rango definido
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand()

0.3699004205404106

In [19]:
np.random.rand(4)

array([0.33756079, 0.89325298, 0.12980026, 0.11322246])

In [20]:
np.random.rand(4,4)

array([[0.74382794, 0.16674896, 0.7668566 , 0.13511405],
       [0.15177502, 0.95844455, 0.78203392, 0.16312841],
       [0.48047882, 0.94191894, 0.66913119, 0.64426351],
       [0.57263044, 0.17700214, 0.89432466, 0.49961109]])

In [21]:
np.random.randint(1,15)

8

In [22]:
np.random.randint(1,100,(10,10))

array([[87, 59, 51,  7,  5,  8,  2, 77, 44, 63],
       [49, 34, 17, 92, 28, 65, 45, 63, 28, 48],
       [ 1, 55, 30, 62, 79, 28, 43, 72, 10, 45],
       [24, 70, 83,  5,  3, 57, 93, 58, 10, 75],
       [21, 91, 23, 18, 90, 64, 96,  1, 60, 26],
       [39, 79, 57, 35, 83,  3, 29, 66, 30, 61],
       [ 2, 31, 15,  8,  6, 88, 28, 76, 29, 70],
       [90,  4, 86,  9, 98, 49, 84,  4, 58, 17],
       [74, 44, 66,  9, 25,  1, 31, 50, 84, 94],
       [16, 30,  5,  3, 95, 33, 62, 56, 23, 49]])

### **Shape y Reshape**
Nos ayuda s identificar las caracteristicas de un arreglo y saber manipularlas

In [23]:
#Devuelve las dimensiones del arreglo
arr = np.random.randint(1,10,(3,2))
arr.shape 


(3, 2)

In [24]:
arr

array([[9, 9],
       [1, 7],
       [8, 6]])

In [25]:
# Cambia la forma del arreglo 
# Reshape, Gives a new shape to an array without changing its data.
arr.reshape(1,6)

array([[9, 9, 1, 7, 8, 6]])

In [26]:
arr.reshape(2,3)

array([[9, 9, 1],
       [7, 8, 6]])

In [27]:
np.reshape(arr,(1,6))

array([[9, 9, 1, 7, 8, 6]])

### **Funciones principales de Numpy**

In [28]:
arr = np.random.randint(1,20,10)
arr

array([11, 11,  7,  4, 10,  1,  8, 13,  8,  2])

In [29]:
matriz = arr.reshape(2,5)
matriz

array([[11, 11,  7,  4, 10],
       [ 1,  8, 13,  8,  2]])

In [30]:
# Devuelve el maximo valor en la matriz
matriz.max()

13

In [31]:
# Devuelve el valor maximo en una fila
matriz.max(1)

array([11, 13])

In [32]:
# Devuelve el indice del el valor maximo que se encuentra ubicado en el vector del array 
arr.argmax()

7

In [33]:
# Devuelve el valor minimo
arr.min()

1

In [34]:
# Pic to Pic, devuelve el valor entre los picos minimo y maximo del array 
arr.ptp()

12

In [35]:
# Retorna el valor que representa la mitad de los datos 
np.percentile(arr,50)

8.0

In [36]:
# Sort ordena el vector de menor a mayor
arr.sort()
arr

array([ 1,  2,  4,  7,  8,  8, 10, 11, 11, 13])

In [37]:
# Calcula la mediana de un numero especifico de datos 
np.median(arr)

8.0

In [38]:
# Calcula la desviacion estandar de un numero especifico de datos
np.std(arr)

3.8275318418009276

In [39]:
# Calcula la varianza de un numero especifico de datos
np.var(arr)

14.65

In [40]:
# Calcula el promedio de un numero especifico de datos 
np.mean(arr)

7.5

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [42]:
a.ndim

2

In [43]:
b.ndim

1

In [44]:
b=np.expand_dims(b,axis=0)
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

###  Condiciones

In [45]:
arr = np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [46]:
indices_cond = arr > 5


In [47]:
indices_cond 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

### Operaciones 

In [49]:
lista = [1,2]
lista

[1, 2]

## **Pandas**

* Pandas series 
* Pandas Dataframe
    * Estructura principal 
    * Arreglo de dos dimenciones 
    * Busqueda por indice (Columnas o Filas ) 
    * Slicing 
    * Operaciones aritmaticas 
    * Distintos tipos de datos
    


In [50]:
import pandas as pd 
psg_players = pd.Series(["Navas","Mbappe", "Neymar", "Messi"],
         index=[1,7,10,30]
         )
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [51]:
dict = {1:"Navas", 7:"Mbappe", 10:"Neymar", 30:"Messi"}
pd.Series(dict)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

### Como lee archivos CSV y JSON con Pandas

In [52]:
pd.read_csv("../input/player-stats-clasificacion/player_stats_clasificacion.csv")

Unnamed: 0        Posición  Edad  Goles por Minuto  \
0              0         Defensa  27.0          0.000326   
1              1  Centrocampista  30.0          0.001442   
2              2  Centrocampista  30.0          0.000000   
3              3       Delantero  30.0          0.000000   
4              4  Centrocampista  26.0          0.001304   
...          ...             ...   ...               ...   
8203        8203       Delantero  31.0          0.000000   
8204        8204       Delantero  29.0          0.024793   
8205        8205  Centrocampista  33.0          0.000000   
8206        8206         Defensa  32.0          0.000000   
8207        8207  Centrocampista  30.0          0.004032   

      Asistencias por Minuto  Goles (sin Penaltis) por Minuto  \
0                   0.000978                         0.000326   
1                   0.000961                         0.000961   
2                   0.001789                         0.000000   
3                   0.000000                         0.000000   
4                   0.000978                         0.000978   
...                      ...                              ...   
8203                0.000000                         0.000000   
8204                0.000000                         0.024793   
8205                0.000000                         0.000000   
8206                0.000000                         0.000000   
8207                0.000000                         0.004032   

      Penaltis Marcados por Minuto  Penaltis Lanzados por Minuto  \
0                         0.000000                      0.000000   
1                         0.000481                      0.000481   
2                         0.000000                      0.000000   
3                         0.000000                      0.000000   
4                         0.000326                      0.000326   
...                            ...                           ...   
8203                      0.000000                      0.000000   
8204                      0.000000                      0.000000   
8205                      0.000000                      0.000000   
8206                      0.000000                      0.000000   
8207                      0.000000                      0.000000   

      Tarjetas Amarillas por Minuto  Tarjetas Rojas por Minuto  ...  \
0                          0.002281                        0.0  ...   
1                          0.000481                        0.0  ...   
2                          0.001789                        0.0  ...   
3                          0.000000                        0.0  ...   
4                          0.001304                        0.0  ...   
...                             ...                        ...  ...   
8203                       0.000000                        0.0  ...   
8204                       0.000000                        0.0  ...   
8205                       0.008097                        0.0  ...   
8206                       0.019231                        0.0  ...   
8207                       0.004032                        0.0  ...   

      Pases Completados por Minuto  Pases Intentados por Minuto  \
0                         0.398827                     0.556533   
1                         0.424315                     0.590581   
2                         0.182469                     0.262970   
3                         0.191677                     0.269861   
4                         0.508966                     0.673948   
...                            ...                          ...   
8203                      0.119205                     0.185430   
8204                      0.429752                     0.528926   
8205                      0.570850                     0.631579   
8206                      0.403846                     0.615385   
8207                      0.689516                     0.822581   

      Pases Completados (%)  