## Curso de Manipulacion y Transformacion de Datos con Pandas y Numpy

## **Numpy Array**

In [1]:
import numpy as np 
import pandas as pd 

### **Array**
* La estructura central de Numpy 
* Representa datos de manera estructurada
* Indexado
* Acceso a uno o muchos elementos

In [2]:
lista = [0,1,2,3,4,5,6,7,8,9]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [4]:
matriz = ([1,2,3],[4,5,6],[7,8,9])
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matriz [0,2]

3

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Slicing**

In [7]:
arr
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
arr = np.array(lista)
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'],
      dtype='|S21')

### **Dimensiones**

In [9]:
'Definiendo un scalar'
scalar = np.array(42)
print (scalar)
scalar.ndim

42


0

In [10]:
'Definiendo un vector'
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [11]:
'Definiendo una matriz'
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2